import Prism from "prismjs";
import "prismjs/components/prism-jsx";
import "prismjs/themes/prism.css";
import { useEffect } from "react";

export default function CodeBlock({ code, language }) {
  useEffect(() => {
    Prism.highlightAll();
  }, [code, language]);

  return (
    <pre className="relative rounded-lg overflow-hidden">
      <code className={`language-${language}`}>
        {code}
      </code>
      <div className="absolute bottom-0 left-0 right-0 bg-gray-800 text-white text-sm p-2 text-center">
        Code snippet image generated by codecapture.app
      </div>
    </pre>
  );
}
